<?php
// module/Album/view/album/album/index.phtml:

$title = 'Master > Products';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('product', ['action' => 'add']) ?>">Add new product</a>
</p>

<table class="table">
<tr>
    <th>Code</th>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($products as $product) : ?>
    <tr>
        <td><?= $this->escapeHtml($product->getCode()) ?></td>
        <td><?= $this->escapeHtml($product->getName()) ?></td>
        <td>
            <a href="<?= $this->url('product', ['action' => 'edit', 'id' => $product->getId()]) ?>">Edit</a>
            <a href="<?= $this->url('product', ['action' => 'delete', 'id' => $product->getId()]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
